#+AUTHOR: kmaki565
* Program name
WinSwitch.exe
* Program summary
A keyboard based window switching tool (Alt-TAB replacement)
* Build environment
Visual Studio Professional 2013
* Dependencies
mfc120u.dll (Visual C++ 2013 Redistributable x86)
* Program description

When launched, the exe stays in the taskbar notification area.
It registers a hotkey (Alt+F1) during startup and unregisters it upon program termination.

To show the app window, you can press Alt+F1 anytime.
In the list control, all visible windows are listed up. You can search window by pressing the beginning character(s) of the process as you may do on Explorer. Also, you can "find" by window title (caption). Press F3 to invoke a find, and find next.

After desired window is selected, you can press enter to bring the window to foreground, or press F4 to close the window.

To terminate the exe, push X button in the dialog, or choose Exit from the taskbar icon.

* Reference
General (adding icon in taskbar notification area)
http://www.codeproject.com/Articles/39189/Shell-Extensibility-Explorer-Desk-Band-Tray-Notifi

In the project, CSortListCtrl class is provided in below site:
http://www.codeproject.com/Articles/1360/Sort-List-Control

To enumerate windows, below project was a good reference:
http://www.nirsoft.net/utils/winexp.html
